org.gradle.configuration-cache=false
kotlin.stdlib.default.dependency=false
org.gradle.java.home=C:\\Program Files\\Java\\jdk-21.0.5

# Performance
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.jvmargs=-Xms512m -Xmx2g -XX:+UseG1GC -XX:SoftRefLRUPolicyMSPerMB=50
kotlin.incremental=true
kotlin.caching.enabled=true
